services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    env_file:
      - cmd/auction/.env
    environment:
      AUCTION_DURATION: ${AUCTION_DURATION:-1m}
      AUCTION_INTERVAL: ${AUCTION_INTERVAL:-20s}
      BATCH_INSERT_INTERVAL: ${BATCH_INSERT_INTERVAL:-20s}
      MAX_BATCH_SIZE: ${MAX_BATCH_SIZE:-4}
    command: sh -c "/auction"
    networks:
      - localNetwork

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - cmd/auction/.env
    volumes:
      - mongo-data:/data/db
    networks:
      - localNetwork

volumes:
  mongo-data:
    driver: local

networks:
  localNetwork:
    driver: bridge